import type { Metadata } from "next";
import localFont from "next/font/local";
import "./global.css";
import Appbar from "../app/layout/Appbar";
import Footer from "../app/layout/Footer";

import Link from "next/link";
import { Control } from "./Control";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Paytrack",
  description: "Generated by minyoung",
  icons: {
    icon: "/favicon.ico",
  },
};

interface Topic {
  id: number;
  title: string;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col">
          <Appbar />
          <div className="flex-grow bg-white mx-8">
            <div className="mx-auto p-4 pt-8 md:pt-16">{children}</div>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
